web:
    address: '127.0.0.1'
    port: 8081

storage:
    type: sqlite
    path: /data/gatus.db

ui:
    title: 'rguixaro.dev /census'
    header: 'rguixaro.dev /census'
    description:
        'Watching the vitals of atrium, receptarium, itinerarium, and compendium'
    logo: 'https://census.rguixaro.dev/favicon.svg'
    link: 'https://rguixaro.dev'
    default-color-scheme: 'light'
    buttons:
        - name: 'Source'
          link: 'https://github.com/rguixaro/census'
        - name: 'Portfolio'
          link: 'https://rguixaro.dev'

alerting:
    telegram:
        token: '${TELEGRAM_BOT_TOKEN}'
        id: '${TELEGRAM_CHAT_ID}'
        default-alert:
            failure-threshold: 3
            success-threshold: 2
            send-on-resolved: true

endpoints:
    - name: 'roots :: atrium'
      group: 'rguixaro.dev'
      url: 'https://roots.rguixaro.dev/api/health'
      interval: 60s
      conditions:
          - '[STATUS] == 200'
          - '[RESPONSE_TIME] < 5000'
      ui:
          hide-conditions: true
          badge:
              response-time:
                  thresholds: [200, 500, 1000, 2000, 3000]
      alerts:
          - type: telegram

    - name: 'cookbook :: receptarium'
      group: 'rguixaro.dev'
      url: 'https://cookbook.rguixaro.dev/api/health'
      interval: 60s
      conditions:
          - '[STATUS] == 200'
          - '[RESPONSE_TIME] < 5000'
      ui:
          hide-conditions: true
          badge:
              response-time:
                  thresholds: [200, 500, 1000, 2000, 3000]
      alerts:
          - type: telegram

    - name: 'rask :: itinerarium'
      group: 'rguixaro.dev'
      url: 'https://rask.rguixaro.dev/api/health'
      interval: 60s
      conditions:
          - '[STATUS] == 200'
          - '[RESPONSE_TIME] < 5000'
      ui:
          hide-conditions: true
          badge:
              response-time:
                  thresholds: [200, 500, 1000, 2000, 3000]
      alerts:
          - type: telegram

    - name: 'portfolio :: compendium'
      group: 'rguixaro.dev'
      url: 'https://portfolio.rguixaro.dev/api/health.json'
      interval: 60s
      conditions:
          - '[STATUS] == 200'
          - '[RESPONSE_TIME] < 5000'
      ui:
          hide-conditions: true
          badge:
              response-time:
                  thresholds: [200, 500, 1000, 2000, 3000]
      alerts:
          - type: telegram
